# Site settings
title: Ursula Siems
email: me@ursulasiems.de
description: "Ursula Siems Heilpraktikerin."
baseurl: ""
url: "http://ursulasiems.de"
twitter_username: ursulasiems
github_username: ursulasiems

# Build settings
markdown: kramdown
permalink: pretty
